- name: Hardening ubuntu
  hosts: myhosts
  vars_prompt:
    - name: luks_passphrase
      prompt: "Enter LUKS disk encryption passphrase"
      private: true
    - name: admin_fullname
      prompt: "Enter admin full name"
      private: false
    - name: admin_email
      prompt: "Enter admin email"
      private: false
    - name: admin_pass
      prompt: "Enter admin password"
      private: true
    - name: pro_token
      prompt: "Enter Ubuntu Pro token"
      private: true

  tasks:
    - name: Hardenening Ubuntu
      ansible.builtin.import_role:
        name: hardened_ubuntu
