- name: Install encrypted ubuntu from rescue
  hosts: myhosts
  gather_facts: false
  vars_prompt:
    - name: luks_passphrase
      prompt: "Enter LUKS disk encryption passphrase"
      private: true

  vars:
    local_public_key: "{{ lookup('env','HOME') }}/.ssh/id_ed25519.pub"
    local_private_key: "{{ lookup('env','HOME') }}/.ssh/id_ed25519"
    dropbear_port: 22

  pre_tasks:
    - name: Remove old SSH key for sv1.cservices.co.il
      delegate_to: localhost
      ansible.builtin.known_hosts:
        path: ~/.ssh/known_hosts
        name: "{{ inventory_hostname }}"
        state: absent

    - name: Accept and store SSH host key permanently
      delegate_to: localhost
      ansible.builtin.shell: |
        ssh -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=~/.ssh/known_hosts \
            -p {{ dropbear_port | default(22) }} \
            root@{{ inventory_hostname }} "echo SSH key accepted"
      register: ssh_key_accept
      changed_when: false
      failed_when: false

  tasks:
    - name: Gather facts manually after cleanup
      ansible.builtin.setup:

    - name: Stop RAID and wipe disks
      ansible.builtin.shell: |
        mdadm --stop /dev/md/* 2>/dev/null || true
        wipefs -fa /dev/nvme*n1
      register: wipe_result
      changed_when: wipe_result.stdout is search("were erased")

    - name: Upload SSH public key
      ansible.builtin.copy:
        src: "{{ local_public_key }}"
        dest: /tmp/authorized_keys
        mode: '0644'

    - name: Upload setup.conf
      ansible.builtin.template:
        src: setup.conf.j2
        dest: /tmp/setup.conf
        mode: '0644'

    - name: Upload post-install script
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/post-install.sh"
        dest: /tmp/post-install.sh
        mode: '0755'

    - name: Run installimage
      ansible.builtin.shell: |
        export TERM=xterm
        git clone --single-branch --branch security-fix-1 https://github.com/lielmazar/installimage.git
        /root/installimage/installimage -a -c /tmp/setup.conf -x /tmp/post-install.sh
      args:
        chdir: /root
      changed_when: true

    - name: Reboot system
      ansible.builtin.command: reboot
      async: 1
      poll: 0
      ignore_errors: true  # since the SSH connection will drop
      register: reboot_result
      changed_when: true

    - name: Wait for dropbear SSH
      delegate_to: localhost
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ dropbear_port }}"
        timeout: 300
        state: started

    - name: Unlock encrypted disk
      delegate_to: localhost
      ansible.builtin.expect:
        command: >
          ssh -o StrictHostKeyChecking=no
              -o UserKnownHostsFile=/dev/null
              -p {{ dropbear_port }}
              -tt root@{{ inventory_hostname }} cryptroot-unlock
        responses:
          '.*unlock.*disk.*:': "{{ luks_passphrase }}"
      register: unlock_result
      failed_when: false   # Dropbear closes the connection after unlocking
      no_log: false        # Prevent logging sensitive information

    - name: Debug unlock result
      when: unlock_result is defined
      changed_when: true
      failed_when: false
      ansible.builtin.debug:
        msg: "Unlock result: {{ unlock_result }}"

    - name: Remove old SSH key for sv1.cservices.co.il after unlock
      ansible.builtin.known_hosts:
        path: ~/.ssh/known_hosts
        name: "{{ inventory_hostname }}"
        state: absent
      delegate_to: localhost

    - name: Wait for SSH
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        timeout: 300
        state: started
      delegate_to: localhost

    - name: Accept and store SSH host key permanently ufter unlock
      delegate_to: localhost
      ansible.builtin.shell: |
        ssh -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=~/.ssh/known_hosts \
            -p {{ dropbear_port | default(22) }} \
            root@{{ inventory_hostname }} "echo SSH key accepted"
      register: ssh_key_accept
      changed_when: false
      failed_when: false

    - name: Upgrade system packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Install unattended-upgrades
      ansible.builtin.apt:
        name: unattended-upgrades
        state: present

    - name: Remove installimage artifacts
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /installimage.conf
        - /installimage.debug
        - /post-install
