    - name: Enable Ubuntu Pro 
      shell: |
        pro attach {{ pro_token }}

    - name: Enable FIPS
      shell: |
        pro enable fips-updates --assume-yes
  
    - name: Autoremove packages
      apt:
        autoremove: yes

    - name: Ensure admin user exists
      user:
        name: admin
        comment: "{{ admin_fullname }} {{ admin_email }}"
        groups: sudo
        append: yes
        password: "{{ admin_pass | password_hash('sha512') }}"

    - name: Lock root account
      user:
        name: root
        password_lock: yes

    - name: Ensure SSH directory for admin
      file:
        path: /home/admin/.ssh
        state: directory
        owner: admin
        group: admin
        mode: '0700'

    - name: Copy admin authorized key
      copy:
        src: "{{ local_public_key }}"
        dest: /home/admin/.ssh/authorized_keys
        owner: admin
        group: admin
        mode: '0600'

    - name: Copy sshd_config
      copy:
        src: "sshd_config"
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'

    - name: Disable Ctrl+Alt+Delete
      systemd:
        name: ctrl-alt-del.target
        masked: yes

    - name: Install nftables
      apt:
        name: nftables
        state: present

    - name: Copy nftables config
      copy:
        src: "nftables.conf"
        dest: /etc/nftables.conf
        mode: '0644'

    - name: Copy nftables rules
      copy:
        src: "nftables.rules"
        dest: /etc/nftables.rules
        mode: '0644'

    - name: Test nftables config
      command: nft -c -f /etc/nftables.conf

    - name: Enable and restart nftables
      service:
        name: nftables
        enabled: yes
        state: restarted

    - name: Restart sshd
      service:
        name: sshd
        state: restarted

    - name: Manually reboot system
      shell: reboot
      async: 1
      poll: 0
      ignore_errors: true  # since the SSH connection will drop
      register: reboot_result

    - name: Wait for dropbear SSH
      delegate_to: localhost
      wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ dropbear_port }}"
        timeout: 300
        state: started

    - name: Unlock encrypted disk
      delegate_to: localhost
      expect:
        command: >
          ssh -vvv -o StrictHostKeyChecking=no
                  -o UserKnownHostsFile=/dev/null
                  -p {{ dropbear_port }}
                  -tt root@{{ inventory_hostname }} cryptroot-unlock
        responses:
          '.*unlock.*disk.*:': "{{ luks_passphrase }}"
      register: unlock_result
      failed_when: false  # Dropbear closes the connection after unlocking
      no_log: true        # Prevent logging sensitive information
    
    - name: Remove old SSH key for sv1.cservices.co.il
      delegate_to: localhost
      shell: ssh-keygen -R sv1.cservices.co.il
      register: ssh_keygen_result
      changed_when: "'updated' in ssh_keygen_result.stdout"

    - name: Wait for SSH
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        timeout: 300
        state: started
      delegate_to: localhost